org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.0
forge_gradle_version=6.0.16
mapping_channel=official
mapping_version=1.20.1

mod_id=forgewebmap
mod_name=ForgeWebMap
mod_version=0.2.0
mod_group_id=com.mentality.forgewebmap
mod_authors=mentality
mod_description=A server-side Forge web map mod for Minecraft 1.20.1.
