package com.mentality.forgewebmap.config;
import org.junit.jupiter.api.Test; import org.junit.jupiter.api.io.TempDir; import java.nio.file.*; import static org.junit.jupiter.api.Assertions.*;
class WebMapConfigTest { @TempDir Path dir;
 @Test void invalidValuesResetToDefaults() throws Exception { Files.writeString(dir.resolve("forgewebmap-common.properties"),"port=0\ntileSize=0\nrenderThreads=0\nmaxTilesPerTick=0\ntilesDirectory=\n");WebMapConfig c=new WebMapConfig(dir);c.load();assertEquals(8123,c.getPort());assertEquals(256,c.getTileSize());assertEquals(1,c.getRenderThreads());assertEquals(1,c.getMaxTilesPerTick());assertEquals("forgewebmap/tiles",c.getTilesDirectory()); }
 @Test void highMalformedAndEmptyWebReset() throws Exception { Files.writeString(dir.resolve("forgewebmap-common.properties"),"port=65536\nrenderThreads=x\nwebDirectory=\n");WebMapConfig c=new WebMapConfig(dir);c.load();assertEquals(8123,c.getPort());assertEquals(1,c.getRenderThreads());assertEquals("forgewebmap/web",c.getWebDirectory()); }
 @Test void unsupportedTileAndExcessiveThreadsReset() throws Exception { Files.writeString(dir.resolve("forgewebmap-common.properties"),"tileSize=128\nrenderThreads=65\n");WebMapConfig c=new WebMapConfig(dir);c.load();assertEquals(256,c.getTileSize());assertEquals(1,c.getRenderThreads()); }
 @Test void snapshotBudgetDefaultMinimumMaximumAndPersistence()throws Exception{WebMapConfig d=new WebMapConfig(dir);d.load();assertEquals(10,d.getMaxSnapshotMillisPerTick());Files.writeString(dir.resolve("forgewebmap-common.properties"),"maxSnapshotMillisPerTick=1\n");WebMapConfig min=new WebMapConfig(dir);min.load();assertEquals(1,min.getMaxSnapshotMillisPerTick());min.save();WebMapConfig r=new WebMapConfig(dir);r.load();assertEquals(1,r.getMaxSnapshotMillisPerTick());Files.writeString(dir.resolve("forgewebmap-common.properties"),"maxSnapshotMillisPerTick=1000\n");WebMapConfig max=new WebMapConfig(dir);max.load();assertEquals(1000,max.getMaxSnapshotMillisPerTick());}
 @Test void malformedSnapshotBudgetResetsToDefault()throws Exception{Files.writeString(dir.resolve("forgewebmap-common.properties"),"maxSnapshotMillisPerTick=bad\n");WebMapConfig c=new WebMapConfig(dir);c.load();assertEquals(10,c.getMaxSnapshotMillisPerTick());}
}
