package com.mentality.fabricwebmap.web;
import com.mentality.fabricwebmap.config.WebMapConfig; import com.mentality.fabricwebmap.player.PlayerMarkerService; import com.mentality.fabricwebmap.player.PlayerMarkerService.PlayerInfo; import com.mentality.fabricwebmap.render.TileRenderManager; import org.junit.jupiter.api.*; import org.junit.jupiter.api.io.TempDir; import java.nio.file.Path; import java.util.*; import java.util.concurrent.*; import static org.junit.jupiter.api.Assertions.*;
class ApiHandlersTest {
 @TempDir Path dir; private TestHttpExchange call(com.sun.net.httpserver.HttpHandler h,String path)throws Exception{TestHttpExchange e=new TestHttpExchange("GET",path);h.handle(e);assertEquals("application/json; charset=utf-8",e.response.getFirst("Content-Type"));return e;}
 @Test void playerMarkersDisabledReturnsEmptyArray()throws Exception{PlayerMarkerService s=new PlayerMarkerService();s.publish(List.of(new PlayerInfo("secret","overworld",1,2,3,4)));s.setEnabled(false);TestHttpExchange e=call(new ApiPlayersHandler(s),"/api/players");assertEquals(200,e.status);assertEquals("[]",e.body());}
 @Test void playerMarkersEnabledSerializesSnapshot()throws Exception{PlayerMarkerService s=new PlayerMarkerService();s.publish(List.of(new PlayerInfo("Alex","the_end",1.5,64,2.25,90)));String b=call(new ApiPlayersHandler(s),"/api/players").body();assertTrue(b.startsWith("[{")&&b.contains("\"name\":\"Alex\"")&&b.contains("\"dimension\":\"the_end\"")&&b.contains("\"x\":1.5")&&b.contains("\"yaw\":90.0"));}
 @Test void playerJsonEscapingIsValid()throws Exception{PlayerMarkerService s=new PlayerMarkerService();s.publish(List.of(new PlayerInfo("a\"b\\c\n","overworld",0,0,0,0)));String b=call(new ApiPlayersHandler(s),"/api/players").body();assertTrue(b.contains("a\\\"b\\\\c\\n"));}
 @Test void biomeLookupSuccessReturnsPayload()throws Exception{ApiBiomeHandler h=new ApiBiomeHandler((d,x,z)->CompletableFuture.completedFuture("minecraft:plains"),()->true,1);TestHttpExchange e=call(h,"/api/biome?dim=overworld&x=1&z=2");assertEquals(200,e.status);assertTrue(e.body().contains("\"id\":\"minecraft:plains\"")&&e.body().contains("\"biome\":\"Plains\""));}
 @Test void biomeLookupTimeoutReturns503()throws Exception{ApiBiomeHandler h=new ApiBiomeHandler((d,x,z)->new CompletableFuture<>(),()->true,1);TestHttpExchange e=call(h,"/api/biome?dim=overworld&x=1&z=2");assertEquals(503,e.status);assertTrue(e.body().contains("error"));}
 @Test void biomeLookupWithoutServerReturns503()throws Exception{TestHttpExchange e=call(new ApiBiomeHandler((d,x,z)->CompletableFuture.completedFuture("minecraft:plains"),()->false,1),"/api/biome?dim=overworld&x=1&z=2");assertEquals(503,e.status);}
 @Test void biomeLookupExceptionReturnsControlledFailure()throws Exception{CompletableFuture<String> f=new CompletableFuture<>();f.completeExceptionally(new IllegalStateException());TestHttpExchange e=call(new ApiBiomeHandler((d,x,z)->f,()->true,1),"/api/biome?dim=overworld&x=1&z=2");assertEquals(503,e.status);assertFalse(e.body().contains("IllegalStateException"));}
 @Test void biomeLookupUnknownDimensionIsRejected()throws Exception{TestHttpExchange e=call(new ApiBiomeHandler((d,x,z)->{fail("must not lookup");return null;},()->true,1),"/api/biome?dim=bad&x=1&z=2");assertEquals(400,e.status);}
 @Test void biomeHandlerWorksAfterWebServiceRecreation()throws Exception{ApiBiomeHandler replacement=new ApiBiomeHandler((d,x,z)->CompletableFuture.completedFuture("minecraft:forest"),()->true,1);assertEquals(200,call(replacement,"/api/biome?dim=overworld&x=1&z=2").status);}
 @Test void statusEnabledAndRunning()throws Exception{String b=call(status(true,true),"/api/status").body();assertTrue(b.contains("\"enabled\":true")&&b.contains("\"serverRunning\":true"));}
 @Test void statusDisabledAndStopped()throws Exception{java.nio.file.Files.writeString(dir.resolve("fabricwebmap-common.properties"),"enabled=false\n");String b=call(status(false,false),"/api/status").body();assertTrue(b.contains("\"enabled\":false")&&b.contains("\"serverRunning\":false"));}
 @Test void statusReflectsStoppedRenderer()throws Exception{assertTrue(call(status(true,true),"/api/status").body().contains("\"renderState\":\"IDLE\""));}
 @Test void statusReflectsUnavailableServer()throws Exception{assertTrue(call(status(true,false),"/api/status").body().contains("\"serverRunning\":false"));}
 @Test void frontendUsesServerRunningFlag()throws Exception{String js=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/resources/web/app.js"));assertTrue(js.contains("data.serverRunning")&&js.contains("setStatus(false)"));}
 private ApiStatusHandler status(boolean web,boolean server)throws Exception{WebMapConfig c=new WebMapConfig(dir);c.load();return new ApiStatusHandler(c,new TileRenderManager(c),()->web,()->server);}
}
